version: '3.9'

services:
  redis:
    image: redis:7.0.5-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - data:/data
    networks:
      - redis-net

volumes:
  data:
  

networks:
  redis-net:
    driver: bridge

